language: python
python:
  - "2.7"
install:
  - pip install -r requirements-dev.txt --use-mirrors
  - pip install pytest-cov==1.8.1 coverage==3.7.1 coveralls==0.5
script:  py.test --cov=art17 testsuite
after_success: coveralls
notifications:
  email:
      recipients:
            - purepython@eaudeweb.ro
