language: python
python:
  - "2.7"
install:
  - pip install -r requirements-dev.txt --trusted-host eggshop.eaudeweb.ro
  - pip install pytest-cov==2.5.0 coverage==3.7.1 coveralls==0.5
before_script:
  - cp settings.py.example instance/test_settings.py && cp settings.py.example instance/settings.py
script:  py.test --cov=art17 testsuite
after_success: coveralls
notifications:
  email:
      recipients:
            - purepython@eaudeweb.ro
