db:
    restart: always
    image: mysql:5.6
    ports: 
        - ":"
    environment:
        MYSQL_ROOT_PASSWORD: 
        MYSQL_USER:
        MYSQL_PASSWORD:
        MYSQL_DATABASE:
web:
    build: ./art17-consultation
    command: 
        python manage.py runserver -p 5000
    volumes:
        - ./art17-consulation/:/art17
    ports:
        - "5000:5000"
    links:
        - db
    env_file:
        - ./dev.env

