version: '2'

services:

  app:
    image: art17-consultation-test
    depends_on:
    - db
    environment:
      - COLLECT_STATIC=yes
      - MIGRATE=no
    env_file:
    - ./docker/db.env
    - ./docker/app.env
    volumes:
    - ./art17:/var/local/art17/art17
    - ./instance:/var/local/art17/instance
    - ./alembic:/var/local/art17/alembic

  db:
    image: mariadb:5.5
    env_file:
    - ./docker/db.env
