version: '2'

services:

  apache:
    image: eeacms/apache:latest
    ports:
    - 80:80
    depends_on:
    - art17-app
    - art17-static
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - apache:/usr/local/apache2/conf

  art17-app:
    image: eeacms/art17-consultation:latest
    ports:
    - "5000:5000"
    depends_on:
    - mysql
    env_file:
    - ../art17.devel.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - staticdata:/var/local/art17/art17/static
    - maps:/var/local/art17-data/maps
    - factsheets:/var/local/art17-data/factsheets
    #- ../../art17:/var/local/art17/art17/
    #command: ["runserver", "-t", "0.0.0.0", "-p", "5000"]
    #command: /usr/bin/tail -f /dev/null

  art17-static:
    image: nginx:alpine
    depends_on:
    - art17-app
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - nginx:/etc/nginx/conf.d
    - staticdata:/var/local/art17/art17/static:ro

  mysql:
    image: mysql:latest
    ports:
    - "3306:3306"
    env_file:
    - ../art17.devel.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - mysqldata:/var/lib/mysql
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  rsync-server:
    image: eeacms/rsync:latest
    depends_on:
    - apache
    - art17-app
    - mysql
    ports:
    - "2222:22/tcp"
    command:
    - server
    env_file:
    - ../rsync.key
    environment:
      TZ: Europe/Copenhagen
    tty: true
    stdin_open: true
    volumes:
    - apache:/usr/local/apache2/conf
    - nginx:/etc/nginx/conf.d
    - mysqldata:/var/lib/mysql
    - maps:/var/local/maps
volumes:
  apache:
    driver: local
  nginx:
    driver: local
  staticdata:
    driver: local
  mysqldata:
    driver: local
  maps:
    driver: local
  factsheets:
    driver: local
