version: '2'

services:

  art17-app:
    image: eeacms/art17-consultation:latest
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - mysql
    env_file:
    - ../art17.staging.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - staticdata:/var/local/art17/art17/static
    - maps:/var/local/art17-data/maps
    - factsheets:/var/local/art17-data/factsheets

  art17-static:
    image: nginx:alpine
    depends_on:
    - art17-app
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - nginx:/etc/nginx/conf.d
    - staticdata:/var/local/art17/art17/static:ro
    - maps:/var/local/art17-data/maps:ro
    - factsheets:/var/local/art17-data/factsheets:ro

  mysql:
    image: mysql:5.6
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    env_file:
    - ../art17.staging.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - mysqldata:/var/lib/mysql
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  rsync-server:
    image: eeacms/rsync:latest
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - art17-app
    - mysql
    ports:
    - "2222:22/tcp"
    command:
    - server
    env_file:
    - ../rsync.key
    environment:
      TZ: Europe/Copenhagen
    tty: true
    stdin_open: true
    volumes:
    - nginx:/etc/nginx/conf.d
    - mysqldata:/var/lib/mysql
    - maps:/var/local/maps

volumes:
  nginx:
    driver: rancher-nfs
  staticdata:
    driver: rancher-nfs
  mysqldata:
    driver: rancher-nfs
  maps:
    driver: rancher-nfs
  factsheets:
    driver: rancher-nfs
